### ISSUE TITLE
Errors when installing from NPM

### ISSUE THREAD

**Issue by FokkeZB** [aponxi/npm-execxi#15]
When I install via NPM, the make generates 2 warnings, 2 errors and then the package unbuilds:

```
➜  tn git:(master) ✗ sudo npm install execxi --save
Password:
npm http GET https://registry.npmjs.org/execxi
npm http 304 https://registry.npmjs.org/execxi

> execxi@1.2.0 preinstall /Users/zandbergen/dev/projects/tn/node_modules/execxi
> make

node-gyp configure build
  CXX(target) Release/obj.target/execxi/execxi.o
In file included from ../execxi.cpp:43:
In file included from ../include/cvv8/convert.hpp:4:
../include/cvv8/detail/convert_core.hpp:592:17: error: cannot use 'throw' with exceptions disabled
                throw std::runtime_error("JSToNative<T&> could not get native pointer. Throwing to avoid de...
                ^
../include/cvv8/detail/convert_core.hpp:2059:17: error: cannot use 'throw' with exceptions disabled
                throw std::range_error(msg.Content().c_str());
                ^
../execxi.cpp:173:31: warning: comparison of integers of different signs: 'int' and 'uint32_t' (aka 'unsigned int')
      [-Wsign-compare]
            for (int i = 0; i < _exitSuccess->Length(); i++) {
                            ~ ^ ~~~~~~~~~~~~~~~~~~~~~~
../execxi.cpp:264:23: warning: comparison of integers of different signs: 'int' and 'uint32_t' (aka 'unsigned int')
      [-Wsign-compare]
    for (int i = 0; i < array->Length(); i++) {
                    ~ ^ ~~~~~~~~~~~~~~~
2 warnings and 2 errors generated.
make[1]: *** [Release/obj.target/execxi/execxi.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/zandbergen/dev/projects/tn/node_modules/execxi
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v0.10.2
gyp ERR! not ok
make: *** [all] Error 1

> execxi@1.2.0 preuninstall /Users/zandbergen/dev/projects/tn/node_modules/execxi
> make clean

rm -r build
unbuild execxi@1.2.0
npm ERR! weird error 2
npm ERR! not ok code 0
```

**Comment by kodie** [comment]
It's almost 2 years after this was closed and I'm still getting the same errors. :(
